---
- hosts: web
  become: yes
  become_method: sudo
  gather_facts: True
  tasks:
    - name: "Functionality check"
      shell:
        
    - name: "Install system updates"
      apt: 
        update_cache: yes
  
    - name: "Install nginx"
      apt: name=nginx state=present